name: gui

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - ipympl
  - ipywidgets
  - jupyterlab
  - traitlets
  - typing-extensions
  - pyqt=5
  - qtpy
  - pyqtgraph
  - cffi
  - psutil
  - requests
  - pyyaml
  - tqdm
  - networkx
  - sympy
  - packaging
  - python-dateutil
  - filelock
  - protobuf
  - fonttools
  - absl-py
  - cycler
  - kiwisolver
  - colorama
  - opencv  # ✅ conda 的 opencv 版本含 contrib
  - jax
  - jaxlib

  - pip:
      - mediapipe==0.10.14
      - ml-dtypes==0.5.0
      - stack-data==0.6.3
      - ultralytics==8.2.50
      - ultralytics-thop==2.0.0
      - sounddevice==0.5.0
      - pure-eval==0.2.3
      - tzdata==2024.1
