# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\V1_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qt_material import apply_stylesheet

# front end
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2485, 798)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 2471, 1000))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.Recording_tab = QtWidgets.QWidget()
        self.Recording_tab.setObjectName("Recording_tab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Recording_tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 2441, 711))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_Recording = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_Recording.setContentsMargins(500, 0, 500, 0)
        self.horizontalLayout_Recording.setSpacing(500)
        self.horizontalLayout_Recording.setObjectName("horizontalLayout_Recording")
        self.rc_Deadlift_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        self.rc_Deadlift_btn.setFont(font)
        self.rc_Deadlift_btn.setObjectName("Deadlift_btn")
        self.horizontalLayout_Recording.addWidget(self.rc_Deadlift_btn)
        self.rc_Benchpress_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        self.rc_Benchpress_btn.setFont(font)
        self.rc_Benchpress_btn.setObjectName("Benchpress_btn")
        self.horizontalLayout_Recording.addWidget(self.rc_Benchpress_btn)
        self.rc_Squat_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        self.rc_Squat_btn.setFont(font)
        self.rc_Squat_btn.setObjectName("Squat_btn")
        self.horizontalLayout_Recording.addWidget(self.rc_Squat_btn)
        self.horizontalLayout_Recording.setStretch(0, 10)
        self.horizontalLayout_Recording.setStretch(1, 10)
        self.horizontalLayout_Recording.setStretch(2, 10)
        self.rc_Benchpress_btn.raise_()
        self.rc_Squat_btn.raise_()
        self.rc_Deadlift_btn.raise_()
        self.tabWidget.addTab(self.Recording_tab, "")
        self.Review_tab = QtWidgets.QWidget()
        self.Review_tab.setObjectName("Review_tab")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.Review_tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 2441, 711))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_Recording_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_Recording_2.setContentsMargins(500, 0, 500, 0)
        self.horizontalLayout_Recording_2.setSpacing(500)
        self.horizontalLayout_Recording_2.setObjectName("horizontalLayout_Recording_2")
        self.rp_Deadlift_btn_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        self.rp_Deadlift_btn_2.setFont(font)
        self.rp_Deadlift_btn_2.setAutoFillBackground(False)
        self.rp_Deadlift_btn_2.setObjectName("Deadlift_btn_2")
        self.horizontalLayout_Recording_2.addWidget(self.rp_Deadlift_btn_2)
        self.rp_Benchpress_btn_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        self.rp_Benchpress_btn_2.setFont(font)
        self.rp_Benchpress_btn_2.setObjectName("Benchpress_btn_2")
        self.horizontalLayout_Recording_2.addWidget(self.rp_Benchpress_btn_2)
        self.rp_Squat_btn_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        self.rp_Squat_btn_2.setFont(font)
        self.rp_Squat_btn_2.setObjectName("Squat_btn_2")
        self.horizontalLayout_Recording_2.addWidget(self.rp_Squat_btn_2)
        self.horizontalLayout_Recording_2.setStretch(0, 10)
        self.horizontalLayout_Recording_2.setStretch(1, 10)
        self.horizontalLayout_Recording_2.setStretch(2, 10)
        self.tabWidget.addTab(self.Review_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CATS Webcamviewer"))
        self.rc_Deadlift_btn.setText(_translate("MainWindow", "Deadlift"))
        self.rc_Benchpress_btn.setText(_translate("MainWindow", "Benchpress"))
        self.rc_Squat_btn.setText(_translate("MainWindow", "Squat"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Recording_tab), _translate("MainWindow", "Recording"))
        self.rp_Deadlift_btn_2.setText(_translate("MainWindow", "Deadlift"))
        self.rp_Benchpress_btn_2.setText(_translate("MainWindow", "Benchpress"))
        self.rp_Squat_btn_2.setText(_translate("MainWindow", "Squat"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Review_tab), _translate("MainWindow", "Replay"))

# back end
class Mainwindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, *args, obj=None, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.ui.rc_Deadlift_btn.clicked.connect(self.rc_Deadlift_clicked())
        self.ui.rc_Benchpress_btn.clicked.connect(self.rc_Benchpress_clicked())
        self.ui.rc_Squat_btn.clicked.connect(self.rc_Squat_clicked())




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    apply_stylesheet(app, theme='dark_amber.xml')
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
