# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\V1_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyautogui
import os  # 用於判斷是否為資料夾與後續 os.system 呼叫

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        screen_width, screen_height = pyautogui.size()
        MainWindow.setObjectName("MainWindow")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(screen_width, screen_height))

        space_10 = screen_width / 256
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_layout.setContentsMargins(space_10, space_10, space_10, space_10)

        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setStyleSheet("""
            QTabBar::tab {
                font-size: 30px;
                font-family: 'Times New Roman';
                color: yellow;
                padding: 10px 20px;
                min-height: 60px;
                min-width: 200px;
            }
            QTabBar::tab:selected {
                border-bottom: 4px solid yellow;
            }
        """)
        self.tabs.setTabBarAutoHide(False)
        self.tabs.tabBar().setExpanding(False)



        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)

        # Recording tab
        self.Recording_tab = QtWidgets.QWidget()
        self.Recording_tab.setObjectName("Recording_tab")
        self.recording_layout = QtWidgets.QVBoxLayout(self.Recording_tab)
        self.recording_layout.setContentsMargins(10, 10, 10, 10)

        self.grid_Layout_recording = QtWidgets.QGridLayout()
        self.grid_Layout_recording.setContentsMargins(0, 0, 0, 0)

        self.manual_checkbox = QtWidgets.QCheckBox(self.Recording_tab)
        self.manual_checkbox.setObjectName("manual_checkbox")
        self.manual_checkbox.setEnabled(False)
        self.manual_checkbox.setChecked(True)
        self.grid_Layout_recording.addWidget(self.manual_checkbox, 0, 0, 1, 1)

        # ▶️ Deadlift button 
        self.rc_Deadlift_btn = QtWidgets.QPushButton(self.Recording_tab)
        self.rc_Deadlift_btn.setObjectName("Deadlift_btn_3")
        self.rc_Deadlift_btn.setText("Deadlift")
        self.rc_Deadlift_btn.setStyleSheet("""
            QPushButton {
                font-size: 48px;
                color: yellow;
                border: 2px solid yellow;
                font-family: 'Times New Roman';
            }
        """)
        self.rc_Deadlift_btn.setFixedSize(800, 120)
        self.grid_Layout_recording.addWidget(self.rc_Deadlift_btn, 1, 0, 1, 1)

        # ▶️ Benchpress button
        self.rc_Benchpress_btn = QtWidgets.QPushButton(self.Recording_tab)
        self.rc_Benchpress_btn.setObjectName("Benchpress_btn_3")
        self.rc_Benchpress_btn.setText("Benchpress")
        self.rc_Benchpress_btn.setStyleSheet("""
            QPushButton {
                font-size: 48px;
                color: yellow;
                border: 2px solid yellow;
                font-family: 'Times New Roman';
            }
        """)
        self.rc_Benchpress_btn.setFixedSize(800, 120)
        self.grid_Layout_recording.addWidget(self.rc_Benchpress_btn, 2, 0, 1, 1)

        # ▶️ Squat button
        self.rc_Squat_btn = QtWidgets.QPushButton(self.Recording_tab)
        self.rc_Squat_btn.setObjectName("Squat_btn_3")
        self.rc_Squat_btn.setText("Squat")
        self.rc_Squat_btn.setStyleSheet("""
            QPushButton {
                font-size: 48px;
                color: yellow;
                border: 2px solid yellow;
                font-family: 'Times New Roman';
            }
        """)
        self.rc_Squat_btn.setFixedSize(800, 120)
        self.grid_Layout_recording.addWidget(self.rc_Squat_btn, 3, 0, 1, 1)


        self.recording_layout.addLayout(self.grid_Layout_recording)

        # Replay tab
        font.setPointSize(18)
        self.Replay_tab = QtWidgets.QWidget()
        self.Replay_tab.setObjectName("Replay_tab")
        self.replay_layout = QtWidgets.QVBoxLayout(self.Replay_tab)
        self.replay_layout.setContentsMargins(10, 10, 10, 10)

        self.top_controls_layout = QtWidgets.QHBoxLayout()

        self.rp_Deadlift_btn = QtWidgets.QPushButton(self.Replay_tab)
        self.rp_Deadlift_btn.setStyleSheet("font-size:18px")
        self.rp_Deadlift_btn.setObjectName("Deadlift_play_btn")
        self.top_controls_layout.addWidget(self.rp_Deadlift_btn)

        self.rp_Benchpress_btn = QtWidgets.QPushButton(self.Replay_tab)
        self.rp_Benchpress_btn.setStyleSheet("font-size:18px")
        self.rp_Benchpress_btn.setObjectName("Benchpress_play_btn")
        self.top_controls_layout.addWidget(self.rp_Benchpress_btn)

        self.rp_Squat_btn = QtWidgets.QPushButton(self.Replay_tab)
        self.rp_Squat_btn.setStyleSheet("font-size:18px")
        self.rp_Squat_btn.setObjectName("Squat_play_btn")
        self.top_controls_layout.addWidget(self.rp_Squat_btn)

        self.File_comboBox = QtWidgets.QComboBox(self.Replay_tab)  # 檔案/資料夾下拉選單
        self.File_comboBox.setObjectName("File_comboBox")  # 設定物件名稱
        self.File_comboBox.setEditable(False)  # 不可編輯
        self.File_comboBox.setStyleSheet("font-size:20px; color:yellow;")  # 字型樣式
        self.File_comboBox.setFixedWidth(800)  # 直接縮短寬度（你可改 400~700 之間微調）
        self.File_comboBox.currentTextChanged.connect(self.handle_file_selection_changed)  # 當選項改變時更新 self.folder
        self.top_controls_layout.addWidget(self.File_comboBox)  # 加到上方控制列

                
        self.search_LineEdit = QtWidgets.QLineEdit(self.Replay_tab)  # 搜尋輸入框
        self.search_LineEdit.setObjectName('search_LineEdit')  # 設定物件名稱
        self.search_LineEdit.setText('請輸入想尋找的文件')  # 預設提示文字
        self.search_LineEdit.setStyleSheet("font-size:20px; color:yellow;")  # 字型樣式
        self.top_controls_layout.addWidget(self.search_LineEdit)  # 加到上方控制列


        self.data_produce_btn_rp = QtWidgets.QPushButton(self.Replay_tab)  # 新增 data produce 按鈕
        self.data_produce_btn_rp.setObjectName("data_produce_btn_rp")  # 設定物件名稱
        self.data_produce_btn_rp.setText("data produce")  # 顯示文字
        self.data_produce_btn_rp.setStyleSheet("font-size:20px; color:yellow; border:1px solid yellow; font-family:'Times New Roman';")  # 外觀樣式
        self.top_controls_layout.addWidget(self.data_produce_btn_rp)  # 放在 search 後方

        self.top_controls_layout.setStretch(0, 1)  # Deadlift 按鈕
        self.top_controls_layout.setStretch(1, 1)  # Benchpress 按鈕
        self.top_controls_layout.setStretch(2, 1)  # Squat 按鈕
        self.top_controls_layout.setStretch(3, 8)  # File_comboBox（已縮短寬度）
        self.top_controls_layout.setStretch(4, 6)  # search_LineEdit
        self.top_controls_layout.setStretch(5, 2)  # data_produce_btn_rp
        
        self.top_controls_layout.setContentsMargins(0, 0, 20, 0)  # 右側保留 20px 內距即可
        self.replay_layout.addLayout(self.top_controls_layout)

        self.play_groupBox = QtWidgets.QGroupBox(self.Replay_tab)
        self.play_groupBox.setObjectName("play_groupBox")
        self.play_layout = QtWidgets.QHBoxLayout()
        self.vision_layout_V = QtWidgets.QVBoxLayout()
        self.data_ctrl_layout_V = QtWidgets.QVBoxLayout()
        self.head_vis_layout = QtWidgets.QGridLayout()
        self.bottom_vis_layout = QtWidgets.QHBoxLayout()
        self.vision_layout_V.addLayout(self.head_vis_layout)
        self.vision_layout_V.addLayout(self.bottom_vis_layout)
        self.play_layout.addLayout(self.vision_layout_V)
        self.play_layout.addLayout(self.data_ctrl_layout_V)
        self.play_groupBox.setLayout(self.play_layout)
        self.replay_layout.addWidget(self.play_groupBox)
        
        self.bottom_controls_layout = QtWidgets.QHBoxLayout()
        self.Play_btn = QtWidgets.QToolButton()
        self.Play_btn.setEnabled(False)
        self.Play_btn.setObjectName("Play_btn")
        self.bottom_controls_layout.addWidget(self.Play_btn)

        self.Stop_btn = QtWidgets.QToolButton()
        self.Stop_btn.setEnabled(False)
        self.Stop_btn.setObjectName("Stop_btn")
        self.bottom_controls_layout.addWidget(self.Stop_btn)

        self.TimeCount_LineEdit = QtWidgets.QLineEdit()
        self.TimeCount_LineEdit.setEnabled(True)
        self.TimeCount_LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.TimeCount_LineEdit.setStyleSheet('color:yellow;')
        self.TimeCount_LineEdit.setReadOnly(True)
        self.TimeCount_LineEdit.setObjectName("TimeCount_LineEdit")

        self.Frameslider = QtWidgets.QSlider()
        self.Frameslider.setGeometry(QtCore.QRect(190, 100, 90, 16))
        self.Frameslider.setEnabled(False)
        self.Frameslider.setOrientation(QtCore.Qt.Horizontal)
        self.Frameslider.setObjectName("Frameslider")

        self.fast_forward_combobox = QtWidgets.QComboBox()
        self.fast_forward_combobox.setEnabled(False)
        self.fast_forward_combobox.setObjectName("fast_forward_combobox")
        self.fast_forward_combobox.setEditable(False)
        self.fast_forward_combobox.setStyleSheet("font-size:20px; color:yellow;")

        self.bottom_controls_layout.addWidget(self.fast_forward_combobox)
        self.bottom_controls_layout.addWidget(self.Frameslider)
        self.bottom_controls_layout.addWidget(self.TimeCount_LineEdit)
        self.bottom_controls_layout.setStretch(0, 0)
        self.bottom_controls_layout.setStretch(1, 0)
        self.bottom_controls_layout.setStretch(2, 0)
        self.bottom_controls_layout.setStretch(3, 90)
        self.bottom_controls_layout.setStretch(4, 5)
        
        self.tabs.addTab(self.Recording_tab, "Recording")
        self.tabs.addTab(self.Replay_tab, 'replay')
        self.main_layout.addWidget(self.tabs)
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CATS Webcamviewer"))
        self.rc_Benchpress_btn.setText(_translate("MainWindow", "Benchpress"))
        self.rc_Squat_btn.setText(_translate("MainWindow", "Squat"))
        self.rc_Deadlift_btn.setText(_translate("MainWindow", "Deadlift"))
        self.manual_checkbox.setText(_translate("MainWindow", "manual recording"))
        self.TimeCount_LineEdit.setPlaceholderText(_translate("MainWindow", "00:00"))
        self.rp_Deadlift_btn.setText(_translate("MainWindow", "Deadlift"))
        self.rp_Benchpress_btn.setText(_translate("MainWindow", "Benchpress"))
        self.rp_Squat_btn.setText(_translate("MainWindow", "Squat"))

    def handle_file_selection_changed(self, text):  # 當 File_comboBox 選項改變
        path = text.strip()  # 取選項文字
        if path and os.path.isdir(path):  # 若是存在的資料夾
            self.folder = path  # 設定為目前資料夾
        else:
            self.folder = None  # 否則清空，避免誤用